#!/usr/bin/python

#  Convert from fits format to a table
#  Copyright (C) 2015 Bob Mottram
#  bob@robotics.uk.to
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
from astropy.io import fits

if len(sys.argv) < 2:
    print "Please specify a fits filename"
    sys.exit(-1)
filename = sys.argv[1]

try:
    hdulist = fits.open(filename)
except:
    print "File not found " + filename
    sys.exit(-2)

listname="PHOTOMETRY"    
scidata = hdulist[listname].data
no_of_fields = len(scidata[0])

# Extract the headers
headers = repr(hdulist[listname].header).split("\n")
col = 0
field_type = []
field_name = []
for h in headers:
    field_type.append(h.split("=")[0].strip())
    name = h.split("=")[1].strip()
    if "'" in name:
        field_name.append(name.split("'")[1].strip())
    else:
        field_name.append("")

# Field name header
sys.stdout.write("| ")
for i in range(len(field_name)):
    if field_type[i].startswith("TTYPE"):
        if i < len(field_name)-1:
            sys.stdout.write(field_name[i] + " ")
        else:
            print field_name[i]

# Field units header
sys.stdout.write("| ")
for i in range(len(field_name)):
    if field_type[i].startswith("TUNIT"):
        if i < len(field_name)-1:
            sys.stdout.write(field_name[i] + " ")
        else:
            print field_name[i]

# Show the data
for i in range(len(scidata)):
    for j in range(no_of_fields):
        if j < no_of_fields-1:
            sys.stdout.write(str(scidata[i][j]) + " ")
        else:
            print scidata[i][j]

sys.exit(0)
