#!/bin/bash
#  Copyright (C) 2015 Bob Mottram
#  bob@robotics.uk.to
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

MIN_PERIOD_DAYS=0.5
MAX_PERIOD_DAYS=4.0

if [ $1 ]; then
    MIN_PERIOD_DAYS=$1
    echo "Minimum orbital period $MIN_PERIOD_DAYS days"
fi

if [ $2 ]; then
    MAX_PERIOD_DAYS=$2
    echo "Maximum orbital period $MAX_PERIOD_DAYS days"
fi

LOG_FILES=*.tbl
for f in $LOG_FILES
do
    echo "Scanning $f"
    waspscan -f $f --min $MIN_PERIOD_DAYS --max $MAX_PERIOD_DAYS
done

LOG_FILES=*.fits
for f in $LOG_FILES
do
    echo "Scanning $f"
    fits2tbl $f > $f.tbl
    if [ -f $f.tbl ]; then
        waspscan -f $f.tbl --min $MIN_PERIOD_DAYS --max $MAX_PERIOD_DAYS
        rm $f.tbl
    fi
done

echo "Done"

exit 0
